// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SyndicateLogic.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tableCurrencies2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tableCurrencies2));
        
        string IMigrationMetadata.Id
        {
            get { return "201610061343148_tableCurrencies2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
