// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SyndicateLogic.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Success : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Success));
        
        string IMigrationMetadata.Id
        {
            get { return "201609021221443_Success"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
