// <auto-generated />
namespace SyndicateLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeMedian : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeMedian));
        
        string IMigrationMetadata.Id
        {
            get { return "201702141827198_removeMedian"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
