// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SyndicateLogic.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class xtbStocks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xtbStocks));
        
        string IMigrationMetadata.Id
        {
            get { return "201702132126013_xtbStocks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
